version: '3'
services:
  web:
    restart: on-failure
    build: .
    image: "ost/rat"
    ports:
      - "8080:8080"
    volumes:
      - ./data/import:/data/import:rw
      - ./config:/config:rw
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=rat
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
  prometheus:
    build: './prometheus'
    ports:
      - "9090:9090"
  grafana:
    build: './grafana'
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus

