{
 "title": "RAT Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage*system_cpu_count",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "sum(jvm_memory_max_bytes)", "legendFormat": "JVM Memory Usage" }
   ]
  },
  {
   "title": "Analytics RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/api/v1/sumByDate\",status=\"200\"}[$__interval])",
     "legendFormat": "Sum by date"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/api/v1/favouriteProducts\",status=\"200\"}[$__interval])",
     "legendFormat": "Favourite products"
    }
   ]
  },
  {
   "title": "Analytics Request Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{uri=\"/api/v1/sumByDate\",status=\"200\"}[$__interval]))",
     "legendFormat": "Sum by date (99p)"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_server_requests_seconds_bucket{uri=\"/api/v1/sumByDate\",status=\"200\"}[$__interval]))",
     "legendFormat": "Sum by date (50p)"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_server_requests_seconds_bucket{uri=\"/api/v1/favouriteProducts\",status=\"200\"}[$__interval]))",
     "legendFormat": "Favourite products (99p)"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_server_requests_seconds_bucket{uri=\"/api/v1/favouriteProducts\",status=\"200\"}[$__interval]))",
     "legendFormat": "Favourite products (50p)"
    }
   ]
  },
  {
   "title": "Receipts Inserts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rat_receipt_save_seconds_count[$__interval])",
     "legendFormat": "Transact/sec"
    }
   ]
  }
 ]
}